<?php
require_once __DIR__ . '/../../config/app.php';
requireLogin();
$filters=sanitizeInput($_GET); $departments=getAllDepartments(); $zones=getAllZones(); $statuses=getAllStatuses();
$summary=getDepartmentDueSummary($filters); $pending=getPendingObservations($filters, 200, 0);
$pageTitle='Department Dues - '.SITE_NAME; require __DIR__.'/../../includes/header.php';
?>
<h2>Department Dues</h2>
<p><a class="plain-link-button" href="<?php echo BASE_URL; ?>modules/reports/export_department_dues_csv.php">Export CSV</a></p>
<form method="get"><table class="form-table filter-table"><tr><td>Department</td><td><select name="department_id"><option value="">All</option><?php foreach($departments as $d): ?><option value="<?php echo e($d['id']); ?>" <?php echo (int)($filters['department_id']??0)===(int)$d['id']?'selected':''; ?>><?php echo e($d['department_name']); ?></option><?php endforeach; ?></select></td><td>Zone</td><td><select name="zone_id"><option value="">All</option><?php foreach($zones as $z): ?><option value="<?php echo e($z['id']); ?>" <?php echo (int)($filters['zone_id']??0)===(int)$z['id']?'selected':''; ?>><?php echo e($z['short_name']); ?></option><?php endforeach; ?></select></td></tr><tr><td>Status</td><td><select name="status_id"><option value="">All Pending</option><?php foreach($statuses as $s): ?><option value="<?php echo e($s['id']); ?>" <?php echo (int)($filters['status_id']??0)===(int)$s['id']?'selected':''; ?>><?php echo e($s['status_name']); ?></option><?php endforeach; ?></select></td><td>Due Till Date</td><td><input type="date" name="due_till_date" value="<?php echo e($filters['due_till_date']??''); ?>" class="date-input"> <input type="submit" value="Search" class="save-button"></td></tr></table></form>
<table class="data-table"><tr><th>S.No.</th><th>Department</th><th>Total Pending</th><th>Open</th><th>Under Review</th><th>Assigned</th><th>Action Taken</th><th>Oldest Pending Date</th></tr><?php foreach($summary as $i=>$r): ?><tr><td><?php echo e($i+1); ?></td><td><?php echo e($r['department_name']); ?></td><td><?php echo e($r['total_pending']); ?></td><td><?php echo e($r['open_count']??0); ?></td><td><?php echo e($r['review_count']??0); ?></td><td><?php echo e($r['assigned_count']??0); ?></td><td><?php echo e($r['action_count']??0); ?></td><td><?php echo e(formatDate($r['oldest_pending_date'])); ?></td></tr><?php endforeach; ?></table>
<h3>Detailed Pending List</h3><table class="data-table"><tr><th>Observation No</th><th>Date</th><th>Zone</th><th>Department</th><th>Specific Area</th><th>Risk</th><th>Status</th><th>Target Date</th><th>Days Pending</th><th>View</th></tr><?php foreach($pending as $r): ?><tr><td><?php echo e($r['observation_no']); ?></td><td><?php echo e(formatDate($r['observation_date'])); ?></td><td><?php echo e($r['short_name']); ?></td><td><?php echo e($r['department_name']); ?></td><td><?php echo e($r['specific_area_location']); ?></td><td><?php echo e($r['risk_level']); ?></td><td><?php echo e($r['status_name']); ?></td><td><?php echo e(formatDate($r['target_closing_date'])); ?></td><td><?php echo e(daysPending($r['observation_date'])); ?></td><td><a href="<?php echo BASE_URL; ?>modules/observations/view.php?id=<?php echo e($r['id']); ?>">View</a></td></tr><?php endforeach; ?></table><p><button class="plain-button" onclick="window.print()">Print</button></p>
<?php require __DIR__.'/../../includes/footer.php'; ?>
