<?php
require_once __DIR__ . '/../../config/app.php';
requireLogin();
$filters=sanitizeInput($_GET); $zones=getAllZones(); $departments=getAllDepartments(); $page=max(1,(int)($filters['page']??1)); $perPage=20; $offset=($page-1)*$perPage;
$rows=getPendingObservations($filters,$perPage,$offset); $all=getPendingObservations($filters,null,null); $total=count($all); $totalPages=max(1,(int)ceil($total/$perPage));
$pageTitle='Pending List - '.SITE_NAME; require __DIR__.'/../../includes/header.php';
?>
<h2>Pending List</h2>
<p><a class="plain-link-button" href="<?php echo BASE_URL; ?>modules/reports/export_pending_csv.php">Export CSV</a></p>
<form method="get"><table class="form-table filter-table"><tr><td>Zone</td><td><select name="zone_id"><option value="">All</option><?php foreach($zones as $z): ?><option value="<?php echo e($z['id']); ?>" <?php echo (int)($filters['zone_id']??0)===(int)$z['id']?'selected':''; ?>><?php echo e($z['short_name']); ?></option><?php endforeach; ?></select></td><td>Department</td><td><select name="department_id"><option value="">All</option><?php foreach($departments as $d): ?><option value="<?php echo e($d['id']); ?>" <?php echo (int)($filters['department_id']??0)===(int)$d['id']?'selected':''; ?>><?php echo e($d['department_name']); ?></option><?php endforeach; ?></select></td></tr><tr><td>Risk Level</td><td><select name="risk_level"><option value="">All</option><?php foreach(['Low','Medium','High','Critical'] as $risk): ?><option value="<?php echo e($risk); ?>" <?php echo ($filters['risk_level']??'')===$risk?'selected':''; ?>><?php echo e($risk); ?></option><?php endforeach; ?></select></td><td>Date</td><td><input type="date" name="from_date" value="<?php echo e($filters['from_date']??''); ?>" class="date-input"> To <input type="date" name="to_date" value="<?php echo e($filters['to_date']??''); ?>" class="date-input"> <input type="submit" value="Search" class="save-button"></td></tr></table></form>
<table class="data-table"><tr><th>S.No.</th><th>Observation No</th><th>Date</th><th>Zone</th><th>Department</th><th>Location</th><th>Description</th><th>Risk</th><th>Status</th><th>Days Pending</th><th>Action</th></tr><?php if(!$rows): ?><tr><td colspan="11">No pending observations found.</td></tr><?php endif; ?><?php foreach($rows as $i=>$r): ?><tr><td><?php echo e($offset+$i+1); ?></td><td><?php echo e($r['observation_no']); ?></td><td><?php echo e(formatDate($r['observation_date'])); ?></td><td><?php echo e($r['short_name']); ?></td><td><?php echo e($r['department_name']); ?></td><td><?php echo e($r['specific_area_location']); ?></td><td><?php echo e(shortText($r['observation_description'],60)); ?></td><td><?php echo e($r['risk_level']); ?></td><td><?php echo e($r['status_name']); ?></td><td><?php echo e(daysPending($r['observation_date'])); ?></td><td><a href="<?php echo BASE_URL; ?>modules/observations/view.php?id=<?php echo e($r['id']); ?>">View</a></td></tr><?php endforeach; ?></table>
<div class="pagination">Page <?php echo e($page); ?> of <?php echo e($totalPages); ?> <?php if($page>1): ?><a href="?<?php echo e(http_build_query(array_merge($filters,['page'=>$page-1]))); ?>">Previous</a><?php endif; ?> <?php if($page<$totalPages): ?><a href="?<?php echo e(http_build_query(array_merge($filters,['page'=>$page+1]))); ?>">Next</a><?php endif; ?></div><p><button class="plain-button" onclick="window.print()">Print</button></p>
<?php require __DIR__.'/../../includes/footer.php'; ?>
