<?php
require_once __DIR__ . '/../../config/app.php';
requireRole([ROLE_ADMIN, ROLE_SAFETY_ADMIN]);
$action=sanitizeInput($_GET['action']??'list'); $id=(int)($_GET['id']??0); $errors=[]; $levels=['Low','Medium','High','Critical'];
if($action==='toggle'&&$id>0){updateRecord("UPDATE observation_categories SET is_active=IF(is_active=1,0,1) WHERE id=?",[$id],'i');logAudit('Toggled category','observation_categories',$id);setFlash('success','Category status updated.');redirect('modules/admin/categories.php');}
$edit=$id>0?fetchOne("SELECT * FROM observation_categories WHERE id=?",[$id],'i'):null; $old=$edit?:['category_name'=>'','description'=>'','severity_level'=>'Low','is_active'=>1];
if(isPost()&&in_array($action,['add','edit'],true)){ $old=array_merge($old,sanitizeInput($_POST)); if(!validateCsrfToken($_POST['csrf_token']??''))$errors[]='Invalid request token.'; if(trim($old['category_name'])==='')$errors[]='Category Name is required.'; if(!in_array($old['severity_level'],$levels,true))$old['severity_level']='Low'; $dup=fetchOne("SELECT id FROM observation_categories WHERE category_name=? AND id<>?",[$old['category_name'],$id],'si'); if($dup)$errors[]='Category already exists.'; if(!$errors){$active=isset($_POST['is_active'])?1:0; if($action==='add'){$newId=insertRecord("INSERT INTO observation_categories (category_name, description, severity_level, is_active) VALUES (?, ?, ?, ?)",[$old['category_name'],$old['description'],$old['severity_level'],$active],'sssi');logAudit('Added category','observation_categories',$newId);}else{updateRecord("UPDATE observation_categories SET category_name=?, description=?, severity_level=?, is_active=? WHERE id=?",[$old['category_name'],$old['description'],$old['severity_level'],$active,$id],'sssii');logAudit('Edited category','observation_categories',$id);} setFlash('success','Category saved successfully.');redirect('modules/admin/categories.php');}}
$pageTitle='Categories - '.SITE_NAME; require __DIR__.'/../../includes/header.php';
?>
<h2>Categories</h2><?php if($errors): ?><div class="flash flash-error"><?php echo e(implode(' ',$errors)); ?></div><?php endif; ?>
<?php if(in_array($action,['add','edit'],true)): ?><form method="post" class="validate-form"><?php echo csrfField(); ?><table class="form-table"><tr><td class="label-cell">Category Name <span class="required">*</span></td><td><input name="category_name" value="<?php echo e($old['category_name']); ?>" class="text-input" data-required="1"></td></tr><tr><td class="label-cell">Description</td><td><input name="description" value="<?php echo e($old['description']); ?>" class="long-input"></td></tr><tr><td class="label-cell">Severity Level</td><td><select name="severity_level"><?php foreach($levels as $l): ?><option value="<?php echo e($l); ?>" <?php echo $old['severity_level']===$l?'selected':''; ?>><?php echo e($l); ?></option><?php endforeach; ?></select></td></tr><tr><td class="label-cell">Active</td><td><input type="checkbox" name="is_active" value="1" <?php echo (int)$old['is_active']===1?'checked':''; ?>></td></tr><tr><td>&nbsp;</td><td><input type="submit" value="Save" class="save-button"> <a class="plain-link-button" href="<?php echo BASE_URL; ?>modules/admin/categories.php">Back</a></td></tr></table></form>
<?php else: $rows=fetchAll("SELECT * FROM observation_categories ORDER BY category_name"); ?><p><a class="plain-link-button" href="<?php echo BASE_URL; ?>modules/admin/categories.php?action=add">Add Category</a></p><table class="data-table"><tr><th>S.No.</th><th>Category Name</th><th>Description</th><th>Severity Level</th><th>Active</th><th>Action</th></tr><?php foreach($rows as $i=>$r): ?><tr><td><?php echo e($i+1); ?></td><td><?php echo e($r['category_name']); ?></td><td><?php echo e($r['description']); ?></td><td><?php echo e($r['severity_level']); ?></td><td><?php echo (int)$r['is_active']?'Yes':'No'; ?></td><td><a href="<?php echo BASE_URL; ?>modules/admin/categories.php?action=edit&id=<?php echo e($r['id']); ?>">Edit</a> <a href="<?php echo BASE_URL; ?>modules/admin/categories.php?action=toggle&id=<?php echo e($r['id']); ?>">Toggle</a></td></tr><?php endforeach; ?></table><?php endif; ?>
<?php require __DIR__.'/../../includes/footer.php'; ?>
