<?php
require_once __DIR__ . '/../../config/app.php';
requireRole([ROLE_ADMIN, ROLE_SAFETY_ADMIN]);
$action=sanitizeInput($_GET['action']??'list'); $id=(int)($_GET['id']??0); $errors=[];
if($action==='toggle'&&$id>0){updateRecord("UPDATE departments SET is_active=IF(is_active=1,0,1) WHERE id=?",[$id],'i');logAudit('Toggled department','departments',$id);setFlash('success','Department status updated.');redirect('modules/admin/departments.php');}
$edit=$id>0?fetchOne("SELECT * FROM departments WHERE id=?",[$id],'i'):null; $old=$edit?:['department_name'=>'','department_code'=>'','is_active'=>1];
if(isPost()&&in_array($action,['add','edit'],true)){ $old=array_merge($old,sanitizeInput($_POST)); if(!validateCsrfToken($_POST['csrf_token']??''))$errors[]='Invalid request token.'; if(trim($old['department_name'])==='')$errors[]='Department Name is required.'; $dup=fetchOne("SELECT id FROM departments WHERE department_name=? AND id<>?",[$old['department_name'],$id],'si'); if($dup)$errors[]='Department already exists.'; if(!$errors){$active=isset($_POST['is_active'])?1:0; if($action==='add'){$newId=insertRecord("INSERT INTO departments (department_name, department_code, is_active) VALUES (?, ?, ?)",[$old['department_name'],$old['department_code'],$active],'ssi');logAudit('Added department','departments',$newId);}else{updateRecord("UPDATE departments SET department_name=?, department_code=?, is_active=? WHERE id=?",[$old['department_name'],$old['department_code'],$active,$id],'ssii');logAudit('Edited department','departments',$id);} setFlash('success','Department saved successfully.');redirect('modules/admin/departments.php');}}
$pageTitle='Departments - '.SITE_NAME; require __DIR__.'/../../includes/header.php';
?>
<h2>Departments</h2><?php if($errors): ?><div class="flash flash-error"><?php echo e(implode(' ',$errors)); ?></div><?php endif; ?>
<?php if(in_array($action,['add','edit'],true)): ?><form method="post" class="validate-form"><?php echo csrfField(); ?><table class="form-table"><tr><td class="label-cell">Department Name <span class="required">*</span></td><td><input name="department_name" value="<?php echo e($old['department_name']); ?>" class="text-input" data-required="1"></td></tr><tr><td class="label-cell">Department Code</td><td><input name="department_code" value="<?php echo e($old['department_code']); ?>" class="text-input"></td></tr><tr><td class="label-cell">Active</td><td><input type="checkbox" name="is_active" value="1" <?php echo (int)$old['is_active']===1?'checked':''; ?>></td></tr><tr><td>&nbsp;</td><td><input type="submit" value="Save" class="save-button"> <a class="plain-link-button" href="<?php echo BASE_URL; ?>modules/admin/departments.php">Back</a></td></tr></table></form>
<?php else: $rows=getDepartments(); ?><p><a class="plain-link-button" href="<?php echo BASE_URL; ?>modules/admin/departments.php?action=add">Add Department</a></p><table class="data-table"><tr><th>S.No.</th><th>Department Name</th><th>Department Code</th><th>Active</th><th>Action</th></tr><?php foreach($rows as $i=>$r): ?><tr><td><?php echo e($i+1); ?></td><td><?php echo e($r['department_name']); ?></td><td><?php echo e($r['department_code']); ?></td><td><?php echo (int)$r['is_active']?'Yes':'No'; ?></td><td><a href="<?php echo BASE_URL; ?>modules/admin/departments.php?action=edit&id=<?php echo e($r['id']); ?>">Edit</a> <a href="<?php echo BASE_URL; ?>modules/admin/departments.php?action=toggle&id=<?php echo e($r['id']); ?>">Toggle</a></td></tr><?php endforeach; ?></table><?php endif; ?>
<?php require __DIR__.'/../../includes/footer.php'; ?>
