<?php
require_once __DIR__ . '/../../config/app.php';
requireRole([ROLE_ADMIN, ROLE_SAFETY_ADMIN]);
$action=sanitizeInput($_GET['action']??'list'); $id=(int)($_GET['id']??0); $errors=[];
if($action==='toggle'&&$id>0){updateRecord("UPDATE safety_zones SET is_active=IF(is_active=1,0,1) WHERE id=?",[$id],'i');logAudit('Toggled zone','safety_zones',$id);setFlash('success','Zone status updated.');redirect('modules/admin/zones.php');}
if($action==='remove_leader'&&$id>0){$zone=(int)($_GET['zone_id']??0);updateRecord("DELETE FROM zone_leaders WHERE id=?",[$id],'i');logAudit('Removed zone leader','zone_leaders',$id);setFlash('success','Zone leader removed.');redirect('modules/admin/zones.php?action=leaders&id='.$zone);}
if($action==='remove_eic'&&$id>0){$zone=(int)($_GET['zone_id']??0);updateRecord("DELETE FROM zone_eic WHERE id=?",[$id],'i');logAudit('Removed zone EIC','zone_eic',$id);setFlash('success','EIC removed.');redirect('modules/admin/zones.php?action=eic&id='.$zone);}
$zone=$id>0?fetchOne("SELECT * FROM safety_zones WHERE id=?",[$id],'i'):null;
$old=$zone?:['zone_code'=>'','zone_name'=>'','short_name'=>'','description'=>'','display_order'=>0,'is_active'=>1];
if(isPost()&&in_array($action,['add','edit'],true)){ $old=array_merge($old,sanitizeInput($_POST)); if(!validateCsrfToken($_POST['csrf_token']??''))$errors[]='Invalid request token.'; if(trim($old['zone_code'])==='')$errors[]='Zone Code is required.'; if(trim($old['zone_name'])==='')$errors[]='Zone Name is required.'; $dup=fetchOne("SELECT id FROM safety_zones WHERE zone_code=? AND id<>?",[$old['zone_code'],$id],'si'); if($dup)$errors[]='Zone Code already exists.'; if(!$errors){$active=isset($_POST['is_active'])?1:0; if($action==='add'){$newId=insertRecord("INSERT INTO safety_zones (zone_code, zone_name, short_name, description, display_order, is_active) VALUES (?, ?, ?, ?, ?, ?)",[$old['zone_code'],$old['zone_name'],$old['short_name'],$old['description'],(int)$old['display_order'],$active],'ssssii');logAudit('Added zone','safety_zones',$newId);}else{updateRecord("UPDATE safety_zones SET zone_code=?, zone_name=?, short_name=?, description=?, display_order=?, is_active=? WHERE id=?",[$old['zone_code'],$old['zone_name'],$old['short_name'],$old['description'],(int)$old['display_order'],$active,$id],'ssssiii');logAudit('Edited zone','safety_zones',$id);} setFlash('success','Zone saved successfully.');redirect('modules/admin/zones.php');}}
if(isPost()&&$action==='leaders'&&$zone){ if(!validateCsrfToken($_POST['csrf_token']??''))$errors[]='Invalid request token.'; $userId=(int)($_POST['user_id']??0); $leaderType=sanitizeInput($_POST['leader_type']??'Zone Leader'); $primary=isset($_POST['is_primary'])?1:0; if($userId<=0)$errors[]='Select leader user.'; if(!$errors){insertRecord("INSERT IGNORE INTO zone_leaders (zone_id, user_id, leader_type, is_primary) VALUES (?, ?, ?, ?)",[$id,$userId,$leaderType,$primary],'iisi');logAudit('Assigned zone leader','zone_leaders',$id);setFlash('success','Leader assigned.');redirect('modules/admin/zones.php?action=leaders&id='.$id);}}
if(isPost()&&$action==='eic'&&$zone){ if(!validateCsrfToken($_POST['csrf_token']??''))$errors[]='Invalid request token.'; $userId=(int)($_POST['user_id']??0); $deptId=(int)($_POST['department_id']??0); if($userId<=0)$errors[]='Select EIC user.'; if(!$errors){insertRecord("INSERT INTO zone_eic (zone_id, user_id, department_id) VALUES (?, ?, ?)",[$id,$userId,($deptId?:null)],'iii');logAudit('Assigned zone EIC','zone_eic',$id);setFlash('success','EIC assigned.');redirect('modules/admin/zones.php?action=eic&id='.$id);}}
$pageTitle='Zones - '.SITE_NAME; require __DIR__.'/../../includes/header.php';
?>
<h2>Zones</h2><?php if($errors): ?><div class="flash flash-error"><?php echo e(implode(' ',$errors)); ?></div><?php endif; ?>
<?php if(in_array($action,['add','edit'],true)): ?>
<form method="post" class="validate-form"><?php echo csrfField(); ?><table class="form-table">
<tr><td class="label-cell">Zone Code <span class="required">*</span></td><td><input name="zone_code" value="<?php echo e($old['zone_code']); ?>" class="text-input" data-required="1"></td></tr>
<tr><td class="label-cell">Zone Name <span class="required">*</span></td><td><input name="zone_name" value="<?php echo e($old['zone_name']); ?>" class="long-input" data-required="1"></td></tr>
<tr><td class="label-cell">Short Name</td><td><input name="short_name" value="<?php echo e($old['short_name']); ?>" class="long-input"></td></tr>
<tr><td class="label-cell">Description</td><td><textarea name="description" rows="3"><?php echo e($old['description']); ?></textarea></td></tr>
<tr><td class="label-cell">Display Order</td><td><input name="display_order" value="<?php echo e($old['display_order']); ?>" class="text-input"></td></tr>
<tr><td class="label-cell">Active</td><td><input type="checkbox" name="is_active" value="1" <?php echo (int)$old['is_active']===1?'checked':''; ?>></td></tr>
<tr><td>&nbsp;</td><td><input type="submit" value="Save" class="save-button"> <a class="plain-link-button" href="<?php echo BASE_URL; ?>modules/admin/zones.php">Back</a></td></tr>
</table></form>
<?php elseif($action==='leaders'&&$zone): $leaders=fetchAll("SELECT zl.*, u.employee_id, u.full_name FROM zone_leaders zl INNER JOIN users u ON u.id=zl.user_id WHERE zl.zone_id=? ORDER BY zl.is_primary DESC,zl.id",[$id],'i'); $leaderUsers=fetchAll("SELECT u.id,u.employee_id,u.full_name,r.role_name FROM users u INNER JOIN roles r ON r.id=u.role_id WHERE r.role_name IN ('ZONE_LEADER','ADMIN','SAFETY_ADMIN') AND u.is_active=1 ORDER BY u.full_name"); ?>
<h3><?php echo e($zone['zone_code'].' - '.$zone['zone_name']); ?></h3><table class="data-table"><tr><th>Name</th><th>Type</th><th>Primary</th><th>Action</th></tr><?php foreach($leaders as $l): ?><tr><td><?php echo e($l['employee_id'].' '.$l['full_name']); ?></td><td><?php echo e($l['leader_type']); ?></td><td><?php echo (int)$l['is_primary']?'Yes':'No'; ?></td><td><a href="<?php echo BASE_URL; ?>modules/admin/zones.php?action=remove_leader&id=<?php echo e($l['id']); ?>&zone_id=<?php echo e($id); ?>">Remove</a></td></tr><?php endforeach; ?></table>
<form method="post"><?php echo csrfField(); ?><table class="form-table"><tr><td class="label-cell">User</td><td><select name="user_id"><option value="">Select</option><?php foreach($leaderUsers as $u): ?><option value="<?php echo e($u['id']); ?>"><?php echo e($u['employee_id'].' '.$u['full_name'].' ('.$u['role_name'].')'); ?></option><?php endforeach; ?></select></td></tr><tr><td class="label-cell">Leader Type</td><td><select name="leader_type"><option>Zone Leader</option><option>Dy. Leader</option><option>Assistant Leader</option></select></td></tr><tr><td class="label-cell">Primary</td><td><input type="checkbox" name="is_primary" value="1"></td></tr><tr><td>&nbsp;</td><td><input type="submit" value="Add Leader" class="save-button"> <a class="plain-link-button" href="<?php echo BASE_URL; ?>modules/admin/zones.php">Back</a></td></tr></table></form>
<?php elseif($action==='eic'&&$zone): $eics=fetchAll("SELECT ze.*, u.employee_id,u.full_name,d.department_name FROM zone_eic ze INNER JOIN users u ON u.id=ze.user_id LEFT JOIN departments d ON d.id=ze.department_id WHERE ze.zone_id=? ORDER BY ze.id",[$id],'i'); $eicUsers=getUserOptionsByRole(ROLE_ENGINEER_INCHARGE); $departments=getDepartments(); ?>
<h3><?php echo e($zone['zone_code'].' - '.$zone['zone_name']); ?></h3><table class="data-table"><tr><th>Name</th><th>Department</th><th>Action</th></tr><?php foreach($eics as $eic): ?><tr><td><?php echo e($eic['employee_id'].' '.$eic['full_name']); ?></td><td><?php echo e($eic['department_name']); ?></td><td><a href="<?php echo BASE_URL; ?>modules/admin/zones.php?action=remove_eic&id=<?php echo e($eic['id']); ?>&zone_id=<?php echo e($id); ?>">Remove</a></td></tr><?php endforeach; ?></table>
<form method="post"><?php echo csrfField(); ?><table class="form-table"><tr><td class="label-cell">EIC User</td><td><select name="user_id"><option value="">Select</option><?php foreach($eicUsers as $u): ?><option value="<?php echo e($u['id']); ?>"><?php echo e($u['employee_id'].' '.$u['full_name']); ?></option><?php endforeach; ?></select></td></tr><tr><td class="label-cell">Department</td><td><select name="department_id"><option value="">Select</option><?php foreach($departments as $d): ?><option value="<?php echo e($d['id']); ?>"><?php echo e($d['department_name']); ?></option><?php endforeach; ?></select></td></tr><tr><td>&nbsp;</td><td><input type="submit" value="Add EIC" class="save-button"> <a class="plain-link-button" href="<?php echo BASE_URL; ?>modules/admin/zones.php">Back</a></td></tr></table></form>
<?php else: $rows=getZones(); ?>
<p><a class="plain-link-button" href="<?php echo BASE_URL; ?>modules/admin/zones.php?action=add">Add Zone</a></p><table class="data-table"><tr><th>S.No.</th><th>Zone Code</th><th>Zone Name</th><th>Short Name</th><th>Active</th><th>Action</th></tr><?php foreach($rows as $i=>$r): ?><tr><td><?php echo e($i+1); ?></td><td><?php echo e($r['zone_code']); ?></td><td><?php echo e($r['zone_name']); ?></td><td><?php echo e($r['short_name']); ?></td><td><?php echo (int)$r['is_active']?'Yes':'No'; ?></td><td><a href="<?php echo BASE_URL; ?>modules/admin/zones.php?action=edit&id=<?php echo e($r['id']); ?>">Edit</a> <a href="<?php echo BASE_URL; ?>modules/admin/zones.php?action=leaders&id=<?php echo e($r['id']); ?>">Leaders</a> <a href="<?php echo BASE_URL; ?>modules/admin/zones.php?action=eic&id=<?php echo e($r['id']); ?>">EIC</a> <a href="<?php echo BASE_URL; ?>modules/admin/zones.php?action=toggle&id=<?php echo e($r['id']); ?>">Toggle</a></td></tr><?php endforeach; ?></table>
<?php endif; ?>
<?php require __DIR__.'/../../includes/footer.php'; ?>
